# Stubs for your_module (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by a script.

from typing import Any, Callable

class PipeValidatorBrokenError(Exception):
    """Exception raised when a pipeline function fails."""
    ...

class NullPipeBrokenError(Exception):
    """Exception raised when a Null value is passed to a pipe."""
    ...

class PipeValidator:
    """Class used to create functions that can be pipelined using the '|' operator."""
    func: Callable[..., Any]

    def __init__(self, func: Callable[..., Any]) -> None: ...

    def __ror__(self, other: Any) -> Any: ...
        # Here, the 'other' parameter and the return type are kept as 'Any' because
        # they can be either simple values or callable functions depending on the use case.

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

class PipeModifier:
    """Class used to create modifier functions that can be pipelined."""
    func: Callable[..., Any]

    def __init__(self, func: Callable[..., Any]) -> None: ...

    def __ror__(self, other: Any) -> Any: ...

    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
